# Generated by Django 3.1.1 on 2020-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20201116_1136'),
        ('nutrition', '0006_auto_20201201_0653'),
    ]

    operations = [
    ]
