# Generated by Django 3.1.1 on 2020-12-05 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_auto_20201103_1537'),
        ('mailer', '0003_auto_20201201_0653'),
    ]

    operations = [
    ]
