# Generated by Django 3.1.1 on 2020-12-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201201_0653'),
        ('core', '0011_auto_20201103_1537'),
    ]

    operations = [
    ]
